{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-usethis
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/usethis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/usethis/usethis_{{ version }}.tar.gz
  sha256: 22aa2b59f36a8701a4648554c7b0e010253bf917a0f431f06efac7d8a6b59854

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-clipr >=0.3.0
    - r-cli
    - r-crayon
    - r-curl >=2.7
    - r-desc
    - r-fs >=1.3.0
    - r-gh >=1.1.0
    - r-git2r >=0.23
    - r-glue >=1.3.0
    - r-purrr
    - r-rematch2
    - r-rlang >=0.4.3
    - r-rprojroot >=1.2
    - r-rstudioapi
    - r-whisker
    - r-withr
    - r-yaml
  run:
    - r-base
    - r-clipr >=0.3.0
    - r-cli
    - r-crayon
    - r-curl >=2.7
    - r-desc
    - r-fs >=1.3.0
    - r-gh >=1.1.0
    - r-git2r >=0.23
    - r-glue >=1.3.0
    - r-purrr
    - r-rematch2
    - r-rlang >=0.4.3
    - r-rprojroot >=1.2
    - r-rstudioapi
    - r-whisker
    - r-withr
    - r-yaml

test:
  commands:
    - $R -e "library('usethis')"           # [not win]
    - "\"%R%\" -e \"library('usethis')\""  # [win]

about:
  home: https://usethis.r-lib.org, https://github.com/r-lib/usethis
  license: GPL-3
  summary: Automate package and project setup tasks that are otherwise performed manually. This includes setting up unit testing, test  coverage, continuous integration, Git, 'GitHub', licenses, 'Rcpp', 'RStudio'  projects, and more.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: usethis
# Title: Automate Package and Project Setup
# Version: 1.5.1
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", role = "aut", comment = c(ORCID = "0000-0003-4757-117X") ), person("Jennifer", "Bryan", , "jenny@rstudio.com", c("aut", "cre"), comment = c(ORCID = "0000-0002-6983-2759") ), person("RStudio", role = c("cph", "fnd")) )
# Description: Automate package and project setup tasks that are otherwise performed manually. This includes setting up unit testing, test  coverage, continuous integration, Git, 'GitHub', licenses, 'Rcpp', 'RStudio'  projects, and more.
# License: GPL-3
# URL: https://usethis.r-lib.org, https://github.com/r-lib/usethis
# BugReports: https://github.com/r-lib/usethis/issues
# Depends: R (>= 3.2)
# Imports: clipr (>= 0.3.0), clisymbols, crayon, curl (>= 2.7), desc, fs (>= 1.3.0), gh, git2r (>= 0.23), glue (>= 1.3.0), purrr, rlang, rprojroot (>= 1.2), rstudioapi, stats, utils, whisker, withr, yaml
# Suggests: covr, knitr, magick, pkgdown (>= 1.1.0), rmarkdown, roxygen2, spelling (>= 1.2), styler (>= 1.0.2), testthat (>= 2.1.0)
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-07-04 07:03:22 UTC; jenny
# Author: Hadley Wickham [aut] (<https://orcid.org/0000-0003-4757-117X>), Jennifer Bryan [aut, cre] (<https://orcid.org/0000-0002-6983-2759>), RStudio [cph, fnd]
# Maintainer: Jennifer Bryan <jenny@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-07-04 11:00:05 UTC
