appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: tgOXV41mRLayRLYu5MPoIg4KppPLS18+KNyCrufI1vc5zZIm6CtA/zFQiBlQplQ9F2ucu00VIn9zEPvET0YE5qCP93SZmt22eAwpUZkvKG3w9McOnhx0pyAfNQy/8rtEs+rlXlr0R604KLDJeAhlB5EmMFkMpY4LVEZ2fx8ryreAQKtEZ0OxRMhoz+zxCTlcJXd0j5BQSgamwFVNxkIV0jRGjLiHcrRj67Nh8Tv5iQwBTOMwU4wXm0tJSAJZ0MU5zwJNahf6Jt/nn+mAjHOosxhBsEswmttslnzUTT5mu2xfEBPk8yrY5hpsNEIv5l4g9wyLeAcqHZUrXdrdZ/poAX0mKmi7G/5Q5mwfomYFa8ctH9pC0doN41RCauuldWLpyf1rvgRnPc8InUMjZrx8bVweXLlpYcfIkOmaU1wvdOpnr7ihUTQwnRSG5IqgWbMdRdWBH3EZ2UogeAWCk3LgnVajZU3mxos438HLgxtBfbHP8BRdj4hXFiimjhtSjuPieVVpoh79A9jPf0neQn8T/AybUkTxMQX9yS+AYxamxbH+VobIwsTdeIAqNYh/bKejbqwEeLsQ3mOSyWPFYtb7TZQxjG48VMrzTLcqI5JbfiP3vLaNpv2r3MAmYFBaEUEo53USbe0vof55ZKMAHsogfvJKmuEQdDMEAM8wdqwJVa8=}
